name: Build and push `aleo-zkwork-prover` docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - aleo/zkwork/prover/**
      - .github/workflows/aleo-zkwork-prover.yml
  pull_request:
    branches:
      - main
    paths:
      - aleo/zkwork/prover/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          file: aleo/zkwork/prover/Dockerfile
          platforms: linux/amd64,linux/arm64
          context: aleo/zkwork/prover
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/zkwork-aleo-prover:latest
            ${{ secrets.DOCKER_USERNAME }}/zkwork-aleo-miner-prover:latest
